### ISSUE TITLE
LTL has TimedPrecedes 

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#111]
I know it is minor issue and because of histrionically we implement LTL after STL.
commit; da05277fec99aaf0c6d5813195b3ec3c27df3803 branch; master.
rtamt/rtamt/ast/visitor/ltl/ASTVisitor.py
LTLASTVisitor
imports,

    from rtamt.node.stl.timed_precedes import TimedPrecedes

**Comment by TomyYamy** [comment]
We may fix it in master, However our refactoring is on going. maybe we may fix it in refactoring branch then marge it into master.

**Comment by nickovic** [comment]
Fixed it in ast-refactoring.
