### ISSUE TITLE
PrecedesBoundedOperation

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#116]
I'm implementing offline STL with new visitor fashion in branch; ast-refactoring
I don't know how I can implement PrecedesBoundedOperation in there. 
It exists only online.

**Comment by nickovic** [comment]
You do not need precedes operator for offline monitoring. It is an auxiliary operator used only during pastification for online monitoring.

**Comment by TomyYamy** [comment]
OK, I got it. but still my understanding is not good enough.
Maybe I need to ask you for commit here.
https://github.com/nickovic/rtamt/blob/372b8dc2e71d1f8ab14de420664cbab585933e09/rtamt/operation/stl/discrete_time/offline/ast_visitor.py#L207

**Comment by TomyYamy** [comment]
offline does not need it, online needs it.
