### ISSUE TITLE
Ast test case fail

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#122]
@nickovic 
Could you please see the latest commit in branch ast-refactoring?

I find test
https://github.com/nickovic/rtamt/blob/b30b9207699f724250db366b50a69cfab8a37af8/tests/python/ast/test_ltl_ast_parser.py
https://github.com/nickovic/rtamt/blob/b30b9207699f724250db366b50a69cfab8a37af8/tests/python/ast/test_ltl_ast_visitor.py
https://github.com/nickovic/rtamt/blob/b30b9207699f724250db366b50a69cfab8a37af8/tests/python/ast/test_stl_ast_parser.py
https://github.com/nickovic/rtamt/blob/b30b9207699f724250db366b50a69cfab8a37af8/tests/python/ast/test_stl_ast_visitor.py

**Comment by nickovic** [comment]
Please check the new commit in the branch ast-refactoring, the tests now pass.
