### ISSUE TITLE
Could you give good exception for AbstractAstVisitor?

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#123]
@nickovic I remember you have idea for better exception for AbstractAstVisitor.

https://github.com/nickovic/rtamt/blob/447d5eb6a13e6cc1854c99f13a4950d069bdb4ba/rtamt/ast/visitor/abstract_ast_visitor.py#L19-L28

Could give me that.

**Comment by TomyYamy** [comment]
@nickovic 
Perhaps will we keep,
visitDefault() for exception raising? If so exception() maybe better...

**Comment by nickovic** [comment]
created a method raise_exception that is called when the node is not a TL node. The method is overwritten depending whether we call STL or LTL visitor and the exception raised is changed accordingly.
