### ISSUE TITLE
what is sat() in PredicateOperation?

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#125]
I did not understand sat() in PredicateOperation even though I know where you use it.
https://github.com/nickovic/rtamt/blob/c495f36ecf32366e6f3b6ced1942e0ce5db20f56/rtamt/operation/stl/dense_time/offline/predicate_operation.py#L39-L66

**Comment by nickovic** [comment]
sat is the qualitative evaluation of the predicate - true or false. It cannot be inferred directly from the quantitative semantics in border cases. For instance
rho(5<5) = 0 and sat(5 < 5) = false
rho(5 <=5) = 0 and sat(5 <= 5) = true

**Comment by TomyYamy** [comment]
I see sat() makes it boolean.
Still I feel we may may merge it with evaluation in some way.
Let me think.
