### ISSUE TITLE
Update ANTLR version

### ISSUE THREAD

**Issue by iporres** [nickovic/rtamt#145]
Can rtamt use a new version of the antrl runtime library?

There seems to be a problem with older versions of antlr4-python3-runtime and new versions of Pyhton. 
See https://stackoverflow.com/questions/46079258/cant-import-module-antlr-mygrammarlexer-and-mygrammarparser/65054963

It is solved if you use  antlr4-python3-runtime==4.9 instead of antlr4-python3-runtime==4.5

**Comment by cirrostratus1** [comment]
The version also interferes with other tools like [hydra](https://hydra.cc) that also use antlr.

**Comment by cirrostratus1** [comment]
Is there any information regarding compatibility for antlr runtime and generated versions (I was unable to find a compatibility matrix)? If there were a more recent version that the generated version could be updated to ([4.6 is from 2016](https://pypi.org/project/antlr4-python3-runtime/#history)) and that is compatible with multiple versions, at least some dependency conflicts with recent tools could be avoided.

**Comment by nickovic** [comment]
I could not find any compatibility information, but by trying different version, everything between v4.5 and 4.9 included seems to work, and 4.10 does not seem to be backwards compatible.

**Comment by nickovic** [comment]
As a compromise, I recompiled the parser and the lexer with ANTLR4 v4.7 (the default version in Ubuntu 18.04 LTS) and updated the setup.py accordingly. However, if one uses in the same flow two applications with ANTLR4 grammars compiled with different versions of ANTLR4, I do not see how to avoid the warning messages.
