### ISSUE TITLE
Separate install_requires=[] for python2 and python3 in setup.py

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#16]
Separate install_requires=[] for python2 and python3 in setup.py

**Comment by TomyYamy** [comment]
I'm searching setup.py setting. It seems setup.py can't support both of 2.7 and 3.6 in the same setup.py.
I guess we had better to manage those 2 version on different branch. Maybe pkg is also need to separate 2.7 and 3.6.

**Comment by nickovic** [comment]
I added the support for Python 2/3 installation in setup.py.
The setup installs both antlr4-python2-runtime and antlr4-python3-runtime.
We then use either pip2 or pip3 to install the library in the proper (python2 or python3) directory.
Depending on which python (2 or 3) is used to invoke the library, the appropriate version of antlr4 is invoked.
