### ISSUE TITLE
AST access

### ISSUE THREAD

**Issue by parvkpr** [nickovic/rtamt#161]
Is there a way to access the underlying AST? I created a specification and parsed it. I could access the AST object by command spec.ast but is there documentation for access to underlying AST methods? (specifically a way to traverse the tree and manipulate it)

**Comment by nickovic** [comment]
There is no specific documentation on how to access the AST. 

The ANTLR4 AST is translated into an internal tree data structure (see `rtamt/syntax/node`).

There are abstract visitors for both the LTL and STL fragments of the AST (see `rtamt/syntax/visitor`). Your visitor should implement one of the visitor "interfaces".

If you would like to make transformations of the AST tree, I suggest to look how the pastification procedure is implemented, as it translates the AST of a bounded-future STL formula into an AST of its equisatisfiable pure past AST (see `rtamt/pastifier`).

I hope this helps.

**Comment by parvkpr** [comment]
Thanks for the information!
