### ISSUE TITLE
Operator of Interval

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#17]
Now ":" is used as Interval operator. Maybe you consider python operator ":".
Perhaps "," is better intuitively.

**Comment by nickovic** [comment]
I added the option to define an interval either in the form [a,b] or [a:b] - both are now accepted as valid. It is in the "consolidation" branch. The issue will be closed once the change is merged to the master branch.

**Comment by TomyYamy** [comment]
Thanks!
