### ISSUE TITLE
About output of formula setting

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#18]
Regarding example,
'''
spec = rtamt.STLIOSpecification(1)
spec.name = 'Example 1'
spec.declare_var('req', 'float')
spec.declare_var('gnt', 'float')
spec.declare_var('out', 'float')
spec.set_var_io_type('req', 'input')
spec.set_var_io_type('gnt', 'output')
spec.spec = 'out = always((req>=3) implies (eventually[0:5](gnt>=3)))'
spec.iosem = 'standard'
'''
Even "out" is not default setting, it does not work when "out" setting is removed.
I think this setting comes from ROS support to output the robustness to the topic.

I think purely python user will not need "out" variable. Further more, I'm sure, how the robustness  output is handling on either "out" variable on spec or "spec" instance itself.

I think "out" setting should be option or encapsulated internal of rtamt.STLIOSpecification class.

**Comment by nickovic** [comment]
Added support for implicit output.
