### ISSUE TITLE
offline STL robustness seems to be different from original STL

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#26]
I'm not sure why, but semantics of offline STL 'standard' seems to be different from typical STL.
![Figure_1](https://user-images.githubusercontent.com/24283885/79716430-a7d19880-82a4-11ea-9759-1892b2742626.png)

**Comment by TomyYamy** [comment]
I understand that comes from semantics difference theoretically.
Could you share us a paper shows the semantics. maybe your
Monitoring temporal properties of continuous signals,
AMT: A property-based monitoring tool for analog systems, or
AMT 2.0: qualitative and quantitative trace analysis with extended signal temporal logic
?

**Comment by nickovic** [comment]
Can you please tell me what is the formula that you are evaluating?

**Comment by TomyYamy** [comment]
In offline STL, I'm thinking,
G(!p->Fp)
G(!p->Gp)
G(F[0,d](p))
I know I need to mitigate those while considering online-STL semantics.

**Comment by TomyYamy** [comment]
I pushed iss26 branch. Please check it,
You need 
```
$ pip install metric-temporal-logic
```

**Comment by TomyYamy** [comment]
How is the question going?

**Comment by TomyYamy** [comment]
Thank you for your explanation. I think I'm closed to understanding. but still I feel I'm not enough.
I think the difference is,
normalSTL: all t \leq t' < |w|           (from now to future)
onlineSTL:  all 0 \leq t' \leq t          (from now to past)
Somehow search direction is different. I guess that is difference of "future operator" (normalSTL) and "past operator" (onlineSTL).
I'd like to understand more. Some of your paper include the semantics?
Will your paper, "On Synthesizing Controllers from Bounded-Response Properties"
https://link.springer.com/content/pdf/10.1007/978-3-540-73368-3_12.pdf
section 3 express it?

**Comment by TomyYamy** [comment]
I understand onlineSTL can be handle in offline fashion and gives same result on online and offline. However, the semantics is different from onlineSTL and normalSTL.

I think we need to discuss how to lead the users.
Personally, I think we can explicitly define future time operators Gf, Ff, Uf, Rf, Nf separate with normal past time operators G,F,U,R,N. Hence, the future time operators can run on offline and online fashion and the past time operators can work on only offline fashion.

I'm intending support both of offline or normal, online STL. Since still it is difficult that users understand the difference between past and future operator, we can express it explicitly. And offline STL is still useful to debug the STL. User can implement the spec step by step, like confirming the feasibility of the spec. with offline-STL then move to online-STL.
What do you think?

**Comment by TomyYamy** [comment]
We find the difference between past operator (online-STL) and future operator (offline-STL). We need to keep in discussion how to handle user-ability.

**Comment by TomyYamy** [comment]
"Monitoring Properties of Analog and Mixed-Signal Circuits"
https://d1wqtxts1xzle7.cloudfront.net/42719870/Monitoring_properties_of_analog_and_mixe20160215-7865-1hw94v2.pdf?1455604107=&response-content-disposition=inline%3B+filename%3DMonitoring_properties_of_analog_and_mixe.pdf&Expires=1592934996&Signature=Y~OKihRCtjiJGfynUEKbkiFqliyJ14lxSccwDp1zVSUnfOhUdnNVqr32aBDl10-F8JHHQXZ8BD3My0BalbyLRBhpwF6-0KRICXpMpCtQY6XcVXCUEmX-UJB0uaQqt840HH4YMGXBN8Ke-godv2nfjUAS34opVF~aDEysk6BoZyYnCG6MpMR5EfxyzVdmjCWPjdYFErCqHQgUydx7mSYkWkrnYCZuRVXhKe4i41KGEzES7qAP8XDQm5nDv~VtnqcLNvLz6u0cDQe2M~i4fwGX9GRet56btCj-QJW3NWqoAQRr~55vqX7y4Wz-ZZA4RFP8QTO2n6pIJR0fYAYQep3G~Q__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA
gives the explanation,

**Comment by TomyYamy** [comment]
Monitoring properties of analog and mixed-signal circuits gives us better understanding of that.
https://d1wqtxts1xzle7.cloudfront.net/42719870/Monitoring_properties_of_analog_and_mixe20160215-7865-1hw94v2.pdf?1455604107=&response-content-disposition=inline%3B+filename%3DMonitoring_properties_of_analog_and_mixe.pdf&Expires=1593032176&Signature=Avkm4SUFiuynDsC9~0DaNMA9YXoe-jcJ64rfjiDiVzuKWWiqZv2A1-OdPBnonjFON2NI6jMGb-atK2zbvM6AALIBvys1H~nbA7l25yrEbBi41GBcJ95kuKt11uAcu05De8n78SouZxmISZrx8XK5WEKehIU5oPvTOYjLXksu846FegNrXsVAi-6Yn-0aT9oxWI9cMZAkpNRk2M02fPtOknJvzihBHEYroBP6E2y3zPSY0fFV4C~~NfuZzZ1XtRuy1d5GqWFofrIR1mCuCbfiAkHxS7xy-XC3rGQ6L~YEBSjKJGAQAQyH~UcqQydTUvdGtRixWXWoNtINJuRLBL1H7A__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA

**Comment by TomyYamy** [comment]
I have understood the difference.
