### ISSUE TITLE
Full C++ support

### ISSUE THREAD

**Issue by emxaz** [nickovic/rtamt#29]
In our project, we're in a position where we may need to convert all of our code to C++, for performance reasons. It's my understanding that some portions of the Python interface aren't directly accessible from C++ -- primarily, the STL specification parsing and update functionality. Is there any plan to expose this functionality to C++? Our goal is to access the same functionality that we currently do, but without touching the Python interface at all.

**Comment by nickovic** [comment]
We did think about a full C++ library (also mainly for the performance reasons) and this idea is in our backlog. We are currently discussing with some folks on providing support to implement it.

**Comment by nickovic** [comment]
Full C++ support was implemented in a separate project. The support is only for the bounded-future subset of STL with discrete-time interpretation. The two projects may diverge in the future.
[https://git-service.ait.ac.at/sct-dse-public/rtamt-cpp](url)
