### ISSUE TITLE
Version miss matching between code and runtime

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#31]
in branch pyt23, when running the evaluator, the warring happens, 
```
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
```
It's just a warring and not big effect.  I rebuild the code side for sure.
It is because of setup.py setting.
I'm not sure how to match the code and runtime version

**Comment by nickovic** [comment]
Changed setup.py to address it.

**Comment by TomyYamy** [comment]
I think master [477fafae0893daa267cfcb500f0789462f301de2] still has the issue.
at rtamt/examples/online_monitors
```
$ python3 online_monitor_ct.py 
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
Robustness offline: [[2, 3.0], [3.5, 1.0], [4.3, -0.10000000000000009], [11, -0.10000000000000009]]
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
Robustness online - step 1: []
Robustness online - step 2: [[2, 3.0], [3.5, 1.0], [4.3, -0.10000000000000009], [5, -0.10000000000000009]]
Robustness online - step 3: [[6.6, -0.10000000000000009]]
Robustness online - step final: [[7.9, -0.10000000000000009], [11, -0.10000000000000009]]
```
Please note that, it is python3 case.

**Comment by TomyYamy** [comment]
Problem is I don't understand the antrl version setting when build, and runtime.

**Comment by TomyYamy** [comment]
Now I understand the mechanism.
1. normal user.
 they will just use runtime and internally our generated parser will work internally.
 What we need to do is, fix development ANTLR4 version and put reliant version of runtime into setup.py
2. Advanced user (who implements TL) 
 We can explain how align it. Just check,
```bash
$ antlr4
ANTLR Parser Generator  Version 4.7.2
```
and run same version of pip install
```bash
$ sudo pip2 install antlr4-python2-runtime==4.7.2
$ sudo pip3 install antlr4-python3-runtime==4.7.2
```

**Comment by TomyYamy** [comment]
For "application user" the counter measure that committing pre-processed antlr parser and fix runtime in python will work.
Still we expect "TL user" who compile parser himself needs additional explanation in README.md.

**Comment by TomyYamy** [comment]
We fixed it with setup file.
        'antlr4-python2-runtime==4.5; python_version<"3"',
        'antlr4-python3-runtime==4.5; python_version>="3"',
