### ISSUE TITLE
Why cmake version 3.12 or higher version is needed?

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#33]
I'm using Ubuntu 18.04. the cmake version is v3.10 in default.
And we can consider Ubuntu 16.04 user also as ROS user.

Why does the latest version need cmake v3.12 or higher version?

**Comment by nickovic** [comment]
The latest version uses cmake v3.12 or higher because of the usage of FindPython2 and FindPython3, which is needed to compile the CPP backend against the desired version of Python.

**Comment by TomyYamy** [comment]
I see it. I find cmake v3.17 works.
Maybe we can put How to update camke  to README.md

**Comment by TomyYamy** [comment]
I added explanation and sent pull request.

**Comment by TomyYamy** [comment]
We can close the issue.
