### ISSUE TITLE
camke update

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#45]
Ubuntu 16.04, 18.04 does not support package cmake ver 3.12. Thus, user need to upgrade cmake.
The problem is some auto-remove of ros packages happens.

```
tar xvf cmake-3.12.0-Linux-x86_64.tar.gz

sudo mv cmake-3.12.0-Linux-x86_64 /opt
sudo apt-get install ros-kinetic-desktop-full

sudo apt-get install ros-kinetic-tmc-desktop-full
sudo ln -s /opt/cmake-3.12.0-c3-Linux-x86_64/bin/* /usr/bin
```

We can provide additional documents for that.

**Comment by Yuji-Date-t** [comment]
test

**Comment by TomyYamy** [comment]
I made instruction for that
