### ISSUE TITLE
spec cpp does not support float time

### ISSUE THREAD

**Issue by Wang4758** [nickovic/rtamt#47]
Hi there,

While trying the provided example in `examples/basic/monitor_basic_cpp.py`, I've found out that if I changed the times in the signals to float number, i.e.:
```
dataSet = {
         'a': [(0., 100.0), (1., -1.0), (2., -2.0)],
         'b': [(0., 20.0), (1., 2.0), (2., -10.0)]
    }
```
I would get the following error:
```
Boost.Python.ArgumentError: Python argument types in
    None.None(Sample, float)
did not match C++ signature:
    None(stl_library::Sample {lvalue}, int)
```
This does not happen for the Python version of `rtamt.STLSpecification`. Is this a bug of the cpp version?

**Comment by nickovic** [comment]
Discrete-time STL is interpreted over discrete time (integers), while the input data has time stamps, I am documenting and adapting the code to make it clear how time is used in RTAMT.

**Comment by nickovic** [comment]
I adapted the way time is treated for discrete-time STL monitors and documented it in the README.md file in branch 'consolidation'. There are also new related tests and examples that were added. Please try it out now, and read the documentation - your feedback is welcome.

**Comment by nickovic** [comment]
This is now merged into the 'master' branch and is considered as closed issue.
