### ISSUE TITLE
NextOperator and PreviousOperator not supported yet?

### ISSUE THREAD

**Issue by Wang4758** [nickovic/rtamt#49]
Hi @nickovic @TomyYamy,

I tried to parse a specification with `next` or `previous` operators but got Syntax errors. I saw [here](https://github.com/nickovic/rtamt/blob/63b3f810f46f5bd7ec25f6b618194c2f112bb71d/rtamt/parser/stl/StlParser.py#L1810) that there are no implementations for token equals the `NextOperator` or `PreviousOperator`. Are these two operators not supported yet? Thanks in advance.

**Comment by nickovic** [comment]
These two operators are not supported yet. They can be easily supported in the discrete-time semantics. I am addressing your other issues at this time and will also provide the implementation of these two operators (for discrete-time interpretation only).

**Comment by Wang4758** [comment]
> These two operators are not supported yet. They can be easily supported in the discrete-time semantics. I am addressing your other issues at this time and will also provide the implementation of these two operators (for discrete-time interpretation only).

Great, thanks!

**Comment by nickovic** [comment]
The previous and next operators are now added (supported by the discrete-time part of the library).
