### ISSUE TITLE
calculate of undefined part of future operators

### ISSUE THREAD

**Issue by Wang4758** [nickovic/rtamt#59]
Hi,

Thanks for the great update. I have read the listed references but still have some trouble understanding the _pastification_ procedure. As the papers state, the pastification is done by postponing the formula evaluation from time index _t_ to the end of the bounded horizon _t+h_ where all the inputs necessary for computing the robustness degree are available. That means the correct robustness value for _t_ will be output at _t+h_. My question is, what will be the output at _[t, t+h-1]_ then? This part should be undefined, but I observed some results from my minimal example that I don't fully understand.

This is the minimal example that I adapted from the given example:
```python
    data1 = {
        'time': [(0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0), (6.0, 6.0)],
        ' req': [(0.0, 6.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 6.0), (5.0, 0.0), (6.0, 0.0)]
    }
    # # stl
    spec = rtamt.STLSpecification(1)
    spec.name = 'HandMadeMonitor'
    spec.declare_var('req', 'float')
    spec.declare_var('out', 'float')
    spec.spec = 'out = (req>=3) and eventually[0, 3](req<=5.)'


    try:
        spec.parse()
    except rtamt.STLParseException as err:
        print('STL Parse Exception: {}'.format(err))
        sys.exit()

    for i in range(len(data1[' req'])):
        rob = spec.update(i, [('req', data1[' req'][i][1])])

        print('Example (a) - STLSpecification: {} standard robustness: {}'.format(i, rob))
```
I got the following results:
```python
Example (a) - STLSpecification: 0 standard robustness: -inf
Example (a) - STLSpecification: 1 standard robustness: -inf
Example (a) - STLSpecification: 2 standard robustness: -inf
Example (a) - STLSpecification: 3 standard robustness: 3.0
Example (a) - STLSpecification: 4 standard robustness: -3.0
Example (a) - STLSpecification: 5 standard robustness: -3.0
Example (a) - STLSpecification: 6 standard robustness: -3.0
```
If I change the specification to 
```python
spec.spec = 'out = eventually[0, 3](req<=5.)'
```
The results become:
```python
Example (a) - STLSpecification: 0 standard robustness: -1.0
Example (a) - STLSpecification: 1 standard robustness: 5.0
Example (a) - STLSpecification: 2 standard robustness: 5.0
Example (a) - STLSpecification: 3 standard robustness: 5.0
Example (a) - STLSpecification: 4 standard robustness: 5.0
Example (a) - STLSpecification: 5 standard robustness: 5.0
Example (a) - STLSpecification: 6 standard robustness: 5.0
```
The robustness degree of the `and` operator should be the `min` value of the robustness of the two operands. But neither of the operands has a robustness of `-inf` so I was wondering how this is defined.

I've tried to understand with the explanation in the README:
```markdown
rho(eventually[a,b] phi,w,t) = -inf                                                     if t+a >= |w|
                               max_{t' in ([0,t] intersect [t+a,t+b])} rho(phi,w,t')    otherwise
```
If we consider the case of `a>=0`, `[0,t] intersect [t+a,t+b]` is non-empty only when `a==0`, and `[0,t] intersect [t+a,t+b]=t`. Therefore, `rho(eventually[a,b] phi,w,t)` becomes `max_{t' in (t)} rho(phi,w,t') = rho(phi, w, t)`, which would explain the `-1` robustness of the previous example, but not the `-inf`. 

I apologize if I miss something in the reading material. I really appreciate your help.

**Comment by nickovic** [comment]
Let:
```python 
phi1 = (req>=3) and eventually[0, 3](req<=5.)
phi2 = eventually[0, 3](req<=5.)
``

Both `phi1` and `phi2` have a bounded horizon of 3. 

Let `psi1` and `psi2` denote the past formulas that are equi-satisfiable to `phi1` and `phi2`, respectively. We have that:
````python
psi1 = once[3,3](req>=3) and once[0,3](req<=5.)
psi2 = once[0, 3](req<=5.)
````

Let me remind you that 
```python
rho(phi1,w,t) = rho(psi1,w,t+3)
rho(phi2,w,t) = rho(psi2,w,t+3)
```

This means that you should discard the first 3 monitoring outputs of your past monitor (the size of the bounded horizon) because these first 3 outputs are meaningless wrt the original spec. 

Now, let me briefly explain your outputs. For example, `rho(psi2,w,0) = rho(once[0,3](req<=5),w,0) = max(rho(req<=5),w,0), rho(req<=5),w,-1),rho(req<=5),w,-2), rho(req<=5),w,-3)) = max(-1,-inf,-inf,-inf) = -1`. One the other hand, `rho(psi1,w,0) = rho(once[3,3](req>=3) and once[0,3](req<=5),w,0) = min(rho(once[3,3](req>=3),w,0), rho(once[0,3](req<=5),w,0)) = min(rho(req>=3,w,-3), -1) = min(-inf,-1) = -inf`. 

I hope that it answers your question.

**Comment by Wang4758** [comment]
Thanks a lot. It did answer my questions very clearly! However, I have another question about the implementation then, shouldn't the `update` and `offline` functions also discard the meaningless part of the evaluation then? For example, for `phi1 = always((req>=3) and eventually[0, 3](req<=5.))` will output the meaningless value of `-inf` for `update` and `offline` functions since `-inf` always dominates in the `min` operator.

**Comment by TomyYamy** [comment]
@nickovic 
Do we fix it?

**Comment by nickovic** [comment]
The design choice is to leave the "meaningless" prefix because this is how the semantics are defined for the past operators. I understand the requirement to drop it, but since we also allow the use of past operators directly in the formula, and not only via pastification, we need to keep it in order to be conform to the semantics. During pastification, the user must be aware of the process and that first N samples are not to be used.
