### ISSUE TITLE
rtamt/rtamt/spec/stl/discrete_time/specification.py:188: SyntaxWarning: "is not" with a literal. Did you mean "!="?   if key is not 'time':

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#69]
I think it is minor issue.
It is on master 172ae2d55524e5495f36a1d32825cf16a4bfdf42
only Ubuntu 20.04 and python 3.8 case, it happens.

**Comment by nickovic** [comment]
fixed the issue.
