### ISSUE TITLE
Does offline STLDiscreteTimeSpecification() support differetn robustness metrics

### ISSUE THREAD

**Issue by yuanzhou-yzhou** [nickovic/rtamt#70]
Hi, if I have the following data: 
data = {
'time': [0, 1, 2, 3, 4, 5, 6],
'x': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
'y': [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
}

How can I use the offline discrete-time monitor to compute OUTPUT_ROBUSTNESS, INPUT_VACUITY, INPUT_ROBUSTNESS, and OUTPUT_VACUITY?
Thank you very much.

**Comment by nickovic** [comment]
I added an example 
`examples\features\ia-semantics\ia_stl_discrete_time_offline_python.py`
to illustrate the use.

I also fixed a bug related to IA semantics, please pull the most recent version from the master branch.

**Comment by yuanzhou-yzhou** [comment]
Hi @nickovic, thank you very much for your hard work. May I confirm whether you have pushed the updates to the master branch or do you mean the 70-IA-semantics branch? I saw the new updates in the 70-IA-semantics branch, not in the master branch.
