### ISSUE TITLE
different robustness result while the predicates are actually equivalent

### ISSUE THREAD

**Issue by xiaoyaooo** [nickovic/rtamt#74]
Hi, Dear Author,

I may have discovered a bug in the robustness calculation.
the specs I used are 
```
spec.spec = '(x>=3) implies (z > x / 2.0 + y / 2.0)'
spec.spec = '(x>=3) implies (z > 0.5 * x + 0.5 * y)'
spec.spec = '(x>=3) implies (z * 2.0 > x + y)'
``` 
the predicates on the right side of the implies operator are all "z>0.5*(x+y)", but in three different forms
For the dataset I used(see below in the code), all cases should be satisfied when the left side predicate is satisfied, which means the output robustness should be inf for the first two time steps and should be greater than zero for the others.
However, the results are different.
```
Output robustness: [[1, inf], [2, inf], [3, 3.7], [4, 4.666666666666667], [5, 5.642857142857143], [6, 6.625]]
Output robustness: [[1, inf], [2, inf], [3, -1.25], [4, -4.0], [5, -7.75], [6, -12.5]]
Output robustness: [[1, inf], [2, inf], [3, 2.0], [4, 2.0], [5, 2.0], [6, 2.0]]
``` 
Only the result of spec "(x>=3) implies (z * 2.0 > x + y)" behaves like how it should be according to rho(phi > psi,w,t) = rho(phi,w,t) - rho(psi,w,t)
the first result is not quite understandable and the second one becomes negative start from time = 3. 

my code is here.
```
import sys
import rtamt

def monitor():
    # data

    dataSet = {
        'time': [1, 2, 3, 4, 5, 6],
        'x': [1, 2, 3, 4, 5, 6],
        'y': [1, 2, 3, 4, 5, 6],
        'z': [2, 3, 4, 5, 6, 7]
    }

    # # OUTPUT ROBUSTNESS
    spec = rtamt.STLSpecification(language=rtamt.Language.PYTHON, semantics=rtamt.Semantics.OUTPUT_ROBUSTNESS)
    spec.name = 'IA-STL discrete-time online Python monitor with OUTPUT ROBUSTNESS semantics'
    spec.declare_var('x', 'float')
    spec.declare_var('y', 'float')
    spec.declare_var('z', 'float')
    spec.set_var_io_type('x', 'input')
    spec.set_var_io_type('y', 'input')
    spec.set_var_io_type('z', 'output')

    # spec.spec = '(x>=3) implies (z > x / 2.0 + y / 2.0)'
    # spec.spec = '(x>=3) implies (z > 0.5 * x + 0.5 * y)'
    spec.spec = '(x>=3) implies (z * 2.0 > x + y)'

    try:
        spec.parse()
    except rtamt.STLParseException as err:
        print('STL Parse Exception: {}'.format(err))
        sys.exit()

    rob = spec.evaluate(dataSet)
    print('Output robustness: ' + str(rob))

if __name__ == '__main__':
    monitor()

```
And actually I think this is not only a problem with the Semantics.OUTPUT_ROBUSTNESS, or the implies operator
the problem still exists even if I change the spec to the following and don't use output_robustness.
```
spec.spec = '(z > x / 2.0 + y / 2.0)'
spec.spec = '(z > 0.5 * x + 0.5 * y)'
spec.spec = '(z * 2.0 > x + y)'
``` 

Would you please confirm this issue? 
Thank you very much in advance.

**Comment by nickovic** [comment]
Thanks for detecting the bug. It was a problem with the operator precedence in the grammar. The problem shall be fixed now. Please check if you are getting now the results that you expect.

**Comment by xiaoyaooo** [comment]
now the results are correct!
Thank you very much!
