### ISSUE TITLE
unit test does not pass even GitHub CI/DI passed

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#77]
At least master 16f3a61 does not pass the unit test, ubuntu18.04 X python2.7.

Perhaps, the GitHub test is missing something.

**Comment by nickovic** [comment]
Fixed the problem:
- The ci yaml file was not correct and Python 2.7 was actually not executed at all
- Two division testes had different behavior in Python 2.7 and 3.x - a division 3/2 was meant to be a division over floats, i.e. 3/2 = 1.5. In Python 2.7, it does integer division, i.e. 3/2 = 1. I changed the input to 3./2.
