### ISSUE TITLE
Robustness of the previous operator at time step 0

### ISSUE THREAD

**Issue by cirrostratus1** [nickovic/rtamt#82]
Hi,
I try to understand the definition of the previous operator at time step 0.
The definition in the [readme](https://github.com/nickovic/rtamt/blob/master/README.md#specification-language) is
```
rho(prev phi,w,t) = inf            if t<=0
                    rho(phi,w,t-1) otherwise
```
So `rho(prev phi, w, 0) = inf` but according to the corresponding [paper](https://arxiv.org/abs/2005.11827) in appendix A the previous operator is defined as `false S phi`. However, when evaluated in rtamt this gives the value of `phi` time step 0.

It would be great if you could clarify this.

I also would like to report two typos in the readme:

* The timed past temporal operator section is labeled with  `% Past untimed temporal operators`
* There is a duplicate  `rho(psi,w,t')` term in the definition of both ` since` operators:
```
rho(phi since[a,b] psi,w,t) = -inf                                                       if t-a < 0 
                              max_{t' in ([0,t] intersect [t-a,t-b]} (min(rho(psi,w,t'), 
                              min_{t'' in (t',t]}rho(psi,w,t') rho(phi,w,t'')))          otherwise
```

**Comment by nickovic** [comment]
All the typos are fixed.

Regarding prev phi defined as false S phi - this is the case under the strict semantics of S:
- (w,t) |= p S q iff \exists t' < t st. (q,t') |= q and forall t'' \in (t',t), (w,t'') |= p

The implementation does not use the strict interpretation of S, hence we will update our ArXiV report accordingly.
