### ISSUE TITLE
Parsing of time literals with sampling rate

### ISSUE THREAD

**Issue by cirrostratus1** [nickovic/rtamt#83]
Maybe a bug:

https://github.com/nickovic/rtamt/blob/e7d24679caadea15fd9e38a570b67c2832f5208f/rtamt/spec/stl/discrete_time/specification_parser.py#L183-L190

`out` is divided by the sampling period twice. Line 188 probably should be probably:
```
out = int(out)
```

Also appearing in the other time literals:

https://github.com/nickovic/rtamt/blob/e7d24679caadea15fd9e38a570b67c2832f5208f/rtamt/spec/stl/discrete_time/specification_parser.py#L212-L217

https://github.com/nickovic/rtamt/blob/e7d24679caadea15fd9e38a570b67c2832f5208f/rtamt/spec/stl/discrete_time/specification_parser.py#L235-L240

Also it would be good to either explicitly state that setting the sampling period only takes effect if done before parsing the formula, or this should be solved by design, e.g., by making the sampling period an argument of the constructor.

**Comment by nickovic** [comment]
Fixed in the 154 branch. Will be merged to the master branch.
