### ISSUE TITLE
Offline Monitors Unexpected Behaviors (Pastification)

### ISSUE THREAD

**Issue by andersonjwan** [nickovic/rtamt#84]
There are currently two offline monitors supported:

- Discrete-Time Offline Monitor
- Dense-Time Offline Monitor

Since these are offline monitors, it _should_ not be required to pastify the specification; however, after parsing, if the specification is **not** pastified using the `pastify` function, then the computated robustness value utilizing the offline `evaluate` method is incorrect in _some_ requirements.

I have provided an example of the circumstance to provide a better insight of the situation below:

```
from rtamt import STLDiscreteTimeSpecification
from rtamt import STLDenseTimeSpecification

class OfflineMonitors():
    def __init__(self):
        self.spec = '(not ((always[0.0, 4.0]((x <= 250.0) and (x >= 240.0))) and (eventually[3.5,4.0]((x <= 240.1) and (x >= 240.0)))))'
        
        self.timestamps = [0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.10, 1.20, 1.30, 1.40, 1.50,
                           1.60, 1.70, 1.80, 1.90, 2.00, 2.10, 2.20, 2.30, 2.40, 2.50, 2.60, 2.70, 2.80, 2.90, 3.00, 3.10,
                           3.20, 3.30, 3.40, 3.50, 3.60, 3.70, 3.80, 3.90, 4.00]

        self.traces = [249.417849029470, 249.180118213827, 248.897264509553, 248.609577840564, 248.345784286698, 248.086322932321,
                       247.796723856985, 247.502420758160, 247.265839343861, 247.091021571948, 246.917939290133, 246.741933208212,
                       246.560045581446, 246.374932530449, 246.196036227890, 246.025731345019, 245.858228791498, 245.682584638373,
                       245.516611830389, 245.352386259783, 245.129787143078, 244.754843052972, 244.288404854755, 243.847446771133,
                       243.527621790248, 243.335119093294, 243.182620041527, 243.031015821590, 242.869852092566, 242.701807474114,
                       242.529569507170, 242.359839270476, 242.193519420642, 242.031821896898, 241.859601111576, 241.644793781977,
                       241.349895515576, 240.970833016066, 240.581169323418, 240.245751257934, 240.016062360962]

        # format data to discrete 'evaluate' function
        self.discrete_data = {'time': self.timestamps, 'x': self.traces}

        # format data to dense 'evaluate' function
        self.dense_data = ('x', list(zip(self.timestamps, self.traces)))

        print('SPECIFICATION: \'' + self.spec + '\'')
        print('EXPECTED VALUE AFTER EVALUATION: {}\n'.format(-0.0160623609618824))


    def discrete_offline_with_pastification(self):
        """
        Discrete Offline Monitor (w/ Pastification)
        """

        print('DISCRETE OFFLINE WITH PASTIFICATION')
        phi = STLDiscreteTimeSpecification()

        phi.set_sampling_period(0.1, 's', 0.1)
        phi.declare_var('x', 'float')
        phi.spec = self.spec

        phi.parse()
        phi.pastify()

        rob = phi.evaluate(self.discrete_data)
        print('\tRESULT: {}\n'.format(rob[-1][1]))


    def discrete_offline_without_pastification(self):
        """
        Discrete Offline Monitor (w/o Pastification)
        """

        print('DISCRETE OFFLINE WITHOUT PASTIFICATION')
        phi = STLDiscreteTimeSpecification()

        phi.set_sampling_period(0.1, 's', 0.1)
        phi.declare_var('x', 'float')
        phi.spec = self.spec

        phi.parse()

        rob = phi.evaluate(self.discrete_data)
        print('\tRESULT: {}\n'.format(rob[-1][1]))


    def dense_offline_with_pastification(self):
        """
        Dense Offline Monitor (w/ Pastification)
        """

        print('DENSE OFFLINE WITH PASTIFICATION')
        phi = STLDenseTimeSpecification()

        phi.set_sampling_period(0.1, 's', 0.1)
        phi.declare_var('x', 'float')
        phi.spec = self.spec

        phi.parse()
        phi.pastify()

        rob = phi.evaluate(self.dense_data)
        print('\tRESULT: {}\n'.format(rob[-1][1]))


    def dense_offline_without_pastification(self):
        """
        Dense Offline Monitor (w/o Pastification)
        """

        print('DENSE OFFLINE WITHOUT PASTIFICATION')
        phi = STLDenseTimeSpecification()

        phi.set_sampling_period(0.1, 's', 0.1)
        phi.declare_var('x', 'float')
        phi.spec = self.spec

        phi.parse()

        rob = phi.evaluate(self.dense_data)
        print('\tRESULT: {}'.format(rob[-1][1]))

if __name__ == '__main__':
    monitors = OfflineMonitors()

    monitors.discrete_offline_with_pastification()
    monitors.discrete_offline_without_pastification()
    monitors.dense_offline_with_pastification()
    monitors.dense_offline_without_pastification()
```

**Comment by TomyYamy** [comment]
I made a branch for that. iss84.

current result is

        $ python2 test_issue_84.py 
        SPECIFICATION: '(not ((always[0.0, 4.0]((x <= 250.0) and (x >= 240.0))) and (eventually[3.5,4.0]((x <= 240.1) and (x >= 240.0)))))'
        EXPECTED VALUE AFTER EVALUATION: -0.0160623609619
        
        DISCRETE OFFLINE WITH PASTIFICATION
                RESULT: -0.016062360962
        
        DISCRETE OFFLINE WITHOUT PASTIFICATION
        Traceback (most recent call last):
          File "test_issue_84.py", line 107, in <module>
            monitors.discrete_offline_without_pastification()
          File "test_issue_84.py", line 63, in discrete_offline_without_pastification
            rob = phi.evaluate(self.discrete_data)
          File "/mnt/data/repos/rtamt/rtamt/spec/stl/discrete_time/specification.py", line 202, in evaluate
            out = self.offline_evaluator.evaluate(self.top, [length])
          File "/mnt/data/repos/rtamt/rtamt/evaluator/stl/offline_evaluator.py", line 32, in evaluate
            sample = self.visit(node, args)
          File "/mnt/data/repos/rtamt/rtamt/ast/visitor/stl/ASTVisitor.py", line 48, in visit
            ast = self.visitNot(element, args)
          File "/mnt/data/repos/rtamt/rtamt/evaluator/stl/offline_evaluator.py", line 182, in visitNot
            in_sample = self.visit(node.children[0], args)
          File "/mnt/data/repos/rtamt/rtamt/ast/visitor/stl/ASTVisitor.py", line 52, in visit
            ast = self.visitAnd(element, args)
          File "/mnt/data/repos/rtamt/rtamt/evaluator/stl/offline_evaluator.py", line 222, in visitAnd
            in_sample_1 = self.visit(node.children[0], args)
          File "/mnt/data/repos/rtamt/rtamt/ast/visitor/stl/ASTVisitor.py", line 102, in visit
            ast = self.visitTimedAlways(element, args)
          File "/mnt/data/repos/rtamt/rtamt/evaluator/stl/offline_evaluator.py", line 338, in visitTimedAlways
            out_sample = monitor.update(in_sample)
          File "/mnt/data/repos/rtamt/rtamt/operation/stl/discrete_time/offline/always_bounded_operation.py", line 10, in update
            out  = [min(samples[j:j+diff+1]) for j in range(self.begin, self.end+1)]
        ValueError: min() arg is an empty sequence

**Comment by TomyYamy** [comment]
@andersonjwan sorry for long delay of reply.
It could be bug.
future temporal operators with offline monitors do not need pastify(). Even applied pastify() the result should be same.

Now we are working for code refactoring and it is good time to fix it too. I'll let you know.

**Comment by TomyYamy** [comment]
@nickovic Do you know why pastify() changes something when the all specs are future-operator in offline case.

**Comment by andersonjwan** [comment]
> @andersonjwan sorry for long delay of reply. It could be bug. future temporal operators with offline monitors do not need pastify(). Even applied pastify() the result should be same.
> 
> Now we are working for code refactoring and it is good time to fix it too. I'll let you know.

@TomyYamy No worries. And, sounds good. I will be sure to keep a lookout and update our dependencies in [PSY-TaLiRo](https://gitlab.com/sbtg/psy-taliro) accordingly when this is fixed.

Thanks for the work @nickovic!

**Comment by nickovic** [comment]
The bug is now fixed.

**Comment by nickovic** [comment]
The corrected code is now included in the master branch
