### ISSUE TITLE
Test cases for library level

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#89]
I think we my think additional test cases for library.
Current test cases in
/rtamt/tests/python/spec/
are brilliant! it has good coverage of test cases. However because it is integration test, we can not run it unless finish all implementation.

I think we need at least ast component and semantics component.
We don't need too many tests like above. Just we would like to know components works separately or not.

**Comment by TomyYamy** [comment]
I guess for AST layer, we may test
1. RTAMT node generation: it is extended from 
2. RTAMT visitor: Check node with name print visitor
3. pastification: It works as optional.

**Comment by TomyYamy** [comment]
@nickovic  
Could you please how you run test so far? I know where is test. but I'm suffering path setting when runs the test cases without install it.

**Comment by TomyYamy** [comment]
@nickovic I think what I need for 1. is some how this.

    import rtamt
    from rtamt.ast.xxxx import PrintNameSpecification
     
      astPaser = STLSpecificationParser()
      astPaser.name = 'STL test'
      astPaser.declare_var('a', 'float')
      astPaser.spec = 'always(a>=2)'
      node = astPaser.parse()

**Comment by nickovic** [comment]
> @nickovic Could you please how you run test so far? I know where is test. but I'm suffering path setting when runs the test cases without install it.

you can run pytest tests/ from the rtamt directory

**Comment by TomyYamy** [comment]
@nickovic 
I know it. in my case, how to set path to current pkg. I find,

    $ PYTHONPATH="<PATH_TO_PKG>"
  
Works well. I can use it as work around.
For sure VScode has the setting, but it does not work some reason in my case...

**Comment by nickovic** [comment]
The tests for the ParserVisitor and the Visitor are now completed, I guess that we can close this issue.
