### ISSUE TITLE
We may eliminate rtamt/rtamt/node/node.py

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#92]
I'm looking commit: c2b6dbdc4edea3946c7cd4c7c5793a96fe577221 branch ast-refactoring,
I feel,
/rtamt/rtamt/node/abstract_node.py
/rtamt/rtamt/node/node.py
are almost same, and we do not need node.py.

I remember we discussed it, but a minor code issue disturbed it.

**Comment by nickovic** [comment]
Eliminated node.py
