### ISSUE TITLE
remove horizon from node.

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#95]
We may remove horizon information and methods from node.
It might go to semantics layer.
The essential issue is how we handle semantic data like, horizon, online-memory etc in semantic layer while handle syntax in AST separately.

**Comment by TomyYamy** [comment]
commit: 5c2e95c branch: ast-refactoring-trial

I find it is in AST layer so far in my trial.
rtamt/rtamt/ast/parser/abstract_ast_paser.py
AbstractAstPaser

    @property
    def horizon(self):
        return self.__horizon

    @horizon.setter
    def horizon(self, horizon):
        self.__horizon = horizon

and AstParserVisitor as well.

@nickovic Do you think we can move it to expected pastifire or semantic layer?

**Comment by nickovic** [comment]
Removed. Now pastification consists of two passes over the ast: 1) computation of the horizon (LTLHorizon and STLHorizon classes), and 2) ast transformation (LTLPastifier and STLPastifier classes).
